In [166]:
import numpy as np 

class InputLayer:
    def __init__(self, num_input):
        self.num_input = num_input
        
    def predict(self, x):
        return x

def reLu(x):
        return np.maximum(0, x)
    
def dReLu(x):
    return 1*(x>0)
    
class Layer:
    def __init__(self, num_input, num_neuron, func='reLu'):
        np.random.seed(10)
        self.weights = np.random.rand(num_neuron, num_input)
        self.bias = np.zeros((num_neuron, 1))
    
    def update(self, update_grad, update_bias, lr):
        self.weights = np.add(self.weights, lr*update_grad)
        self.bias = np.add(self.bias, lr*update_bias)
    
    def backError(self):
        return np.vectorize(dReLu)(self.z)
        
    def predict(self, prev_activation):
        #print('hey')
        #print(self.weights)
        #print(prev_activation)
        self.z = np.matmul(self.weights, prev_activation)
        #print('zz')
        #print(self.z)
        a = np.vectorize(reLu)(np.add(self.z, self.bias))
        return a
    
    
        

In [176]:
np.random.seed(2)
data = np.random.rand(3,3)
y = np.array([[1], [1], [0]])
data

array([[0.4359949 , 0.02592623, 0.54966248],
       [0.43532239, 0.4203678 , 0.33033482],
       [0.20464863, 0.61927097, 0.29965467]])

In [190]:
np.reshape(data[3], (-1,1))

IndexError: index 3 is out of bounds for axis 0 with size 3

In [177]:
y

array([[1],
       [1],
       [0]])

In [174]:

data2

array([[0.43532239],
       [0.4203678 ],
       [0.33033482]])

In [137]:
aa = Layer(3, 2)
aa.weights

array([[0.77132064, 0.02075195, 0.63364823],
       [0.74880388, 0.49850701, 0.22479665]])

In [138]:
aa.bias

array([[0.],
       [0.]])

In [139]:
aa.predict(data)
aa.backError()

hey
[[0.77132064 0.02075195 0.63364823]
 [0.74880388 0.49850701 0.22479665]]
[[0.4359949 ]
 [0.02592623]
 [0.54966248]]
zz
[[0.68512255]
 [0.46296137]]


array([[1],
       [1]])

In [167]:
class model:
    def __init__(self):
        #l1 = Inputlayer(3)
        self.l2 = Layer(3, 2, 'reLu')
        self.l3 = Layer(2, 2, 'reLu')
        self.l4 = Layer(2, 1, 'reLu')
        
        self.layers = []
    
    def add(self, val, inputLayer=False):
        self.shape.append(val)
        return 0
    
    def compil(self):
        self.calcVals = np.zeros(np.sum(self.shape))
        
        num = 0
        
        for i in range(len(self.shape)-1):
            num += (self.shape[i]+1)*self.shape[i+1]
        
    def fit(self, X, y, lr=0.1):
        l1_act = X #l1.predict(X)
        #print(self.l2.predict(l1_act))
        l2_act = self.l2.predict(l1_act)
        l3_act = self.l3.predict(l2_act)
        l4_act = self.l4.predict(l3_act)
        #print(l2_act)
        #print(l3_act)
        print(l4_act)

        error = np.subtract(y, l4_act)
        
        d_error = 2*error
        
        l4_error = np.multiply(d_error, self.l4.backError())
        #print('l4 err', l4_error.shape)
        l4_grad = np.matmul(l4_error, l3_act.T)
        #print('l4 grad', l4_error.shape)
        #print(self.l4.weights)
        #print(l4_error)
        l3_temp = np.matmul(self.l4.weights.T, l4_error)
        #print('l3 temperr', l4_error.shape)
        l3_error = np.multiply(l3_temp, self.l3.backError())
        #print('l3 err', l4_error.shape)
        l3_grad = np.matmul(l3_error, l2_act.T)
        
        l2_error = np.multiply(np.matmul(self.l3.weights.T, l3_error), self.l2.backError())
        
        l2_grad = np.matmul(l2_error, l1_act.T)
        
        self.l4.update(l4_grad, l4_error, lr)
        self.l3.update(l3_grad, l3_error, lr)
        self.l2.update(l2_grad, l2_error, lr)
        
        return 0
        

In [168]:
test = model()
test.fit(data, y)

[[0.43121709]]


0

In [194]:
#for i in range(1000):
#    for j in range(3):
#        test.fit(np.reshape(data[j], (-1, 1)), np.reshape(y[j], (-1, 1)))